CREATE TABLE IF NOT EXISTS roles (
     id   BIGINT AUTO_INCREMENT PRIMARY KEY,
     role VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO roles (role)
SELECT 'ADMIN'
    WHERE NOT EXISTS (SELECT 1 FROM roles WHERE role = 'ADMIN');

INSERT INTO roles (role)
SELECT 'USER'
    WHERE NOT EXISTS (SELECT 1 FROM roles WHERE role = 'USER');
